default_agent: faiston_inventory_orchestration
agents:
  faiston_inventory_orchestration:
    name: faiston_inventory_orchestration
    entrypoint: main.py
    deployment_type: direct_code_deploy
    runtime_type: PYTHON_3_11
    platform: linux/arm64
    container_runtime: null
    source_path: .
    aws:
      execution_role: arn:aws:iam::377311924364:role/faiston-one-sga-agentcore-role
      execution_role_auto_create: false
      account: '377311924364'
      region: us-east-2
      ecr_repository: null
      ecr_auto_create: false
      s3_path: null
      s3_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: null
        max_lifetime: null
    bedrock_agentcore:
      agent_id: faiston_inventory_orchestration-TOk9YDGFSo
      agent_arn: arn:aws:bedrock-agentcore:us-east-2:377311924364:runtime/faiston_inventory_orchestration-TOk9YDGFSo
      agent_session_id: null
    codebuild:
      project_name: null
      execution_role: null
      source_bucket: null
    memory:
      mode: NO_MEMORY
      memory_id: null
      memory_arn: null
      memory_name: null
      event_expiry_days: 30
      first_invoke_memory_check_done: false
      was_created_by_toolkit: false
    identity:
      credential_providers: []
      workload: null
    aws_jwt:
      enabled: false
      audiences: []
      signing_algorithm: ES384
      issuer_url: null
      duration_seconds: 300
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
    api_key_env_var_name: null
    api_key_credential_provider_name: null
    is_generated_by_agentcore_create: false
  faiston_sga_inventory_hub:
    name: faiston_sga_inventory_hub
    entrypoint: agents/orchestrators/inventory_hub/main.py
    deployment_type: direct_code_deploy
    runtime_type: PYTHON_3_11
    platform: linux/arm64
    container_runtime: null
    source_path: .
    aws:
      execution_role: arn:aws:iam::377311924364:role/faiston-one-sga-agentcore-role
      execution_role_auto_create: false
      account: '377311924364'
      region: us-east-2
      ecr_repository: null
      ecr_auto_create: false
      s3_path: null
      s3_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: A2A
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: 300
        max_lifetime: 3600
    bedrock_agentcore:
      agent_id: faiston_sga_inventory_hub-Rl6ek6Ev3l
      agent_arn: arn:aws:bedrock-agentcore:us-east-2:377311924364:runtime/faiston_sga_inventory_hub-Rl6ek6Ev3l
      agent_session_id: null
    codebuild:
      project_name: null
      execution_role: null
      source_bucket: null
    memory:
      mode: STM_ONLY
      memory_id: faiston_sga_inventory_hub_mem-FJOrX7Cp8g
      memory_arn: arn:aws:bedrock-agentcore:us-east-2:377311924364:memory/faiston_sga_inventory_hub_mem-FJOrX7Cp8g
      memory_name: faiston_sga_inventory_hub_mem
      event_expiry_days: 7
      first_invoke_memory_check_done: true
      was_created_by_toolkit: false
    identity:
      credential_providers: []
      workload: null
    aws_jwt:
      enabled: false
      audiences: []
      signing_algorithm: ES384
      issuer_url: null
      duration_seconds: 300
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
    api_key_env_var_name: null
    api_key_credential_provider_name: null
    is_generated_by_agentcore_create: false
  faiston_inventory_analyst:
    name: faiston_inventory_analyst
    entrypoint: agents/specialists/inventory_analyst/main.py
    deployment_type: direct_code_deploy
    runtime_type: PYTHON_3_11
    platform: linux/arm64
    container_runtime: null
    source_path: .
    aws:
      execution_role: arn:aws:iam::377311924364:role/faiston-one-sga-agentcore-role
      execution_role_auto_create: false
      account: '377311924364'
      region: us-east-2
      ecr_repository: null
      ecr_auto_create: false
      s3_path: null
      s3_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: A2A
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: 300
        max_lifetime: 3600
    bedrock_agentcore:
      agent_id: faiston_inventory_analyst-0uGg1W8ITM
      agent_arn: arn:aws:bedrock-agentcore:us-east-2:377311924364:runtime/faiston_inventory_analyst-0uGg1W8ITM
      agent_session_id: null
    codebuild:
      project_name: null
      execution_role: null
      source_bucket: null
    memory:
      mode: STM_ONLY
      memory_id: faiston_inventory_analyst_mem-gH7dLRDisw
      memory_arn: arn:aws:bedrock-agentcore:us-east-2:377311924364:memory/faiston_inventory_analyst_mem-gH7dLRDisw
      memory_name: faiston_inventory_analyst_mem
      event_expiry_days: 7
      first_invoke_memory_check_done: true
      was_created_by_toolkit: false
    identity:
      credential_providers: []
      workload: null
    aws_jwt:
      enabled: false
      audiences: []
      signing_algorithm: ES384
      issuer_url: null
      duration_seconds: 300
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
    api_key_env_var_name: null
    api_key_credential_provider_name: null
    is_generated_by_agentcore_create: false
  faiston_schema_mapper:
    name: faiston_schema_mapper
    entrypoint: agents/specialists/schema_mapper/main.py
    deployment_type: direct_code_deploy
    runtime_type: PYTHON_3_11
    platform: linux/arm64
    container_runtime: null
    source_path: .
    aws:
      execution_role: arn:aws:iam::377311924364:role/faiston-one-sga-agentcore-role
      execution_role_auto_create: false
      account: '377311924364'
      region: us-east-2
      ecr_repository: null
      ecr_auto_create: false
      s3_path: null
      s3_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: A2A
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: 300
        max_lifetime: 3600
    bedrock_agentcore:
      agent_id: faiston_schema_mapper-7fxI9bFHzd
      agent_arn: arn:aws:bedrock-agentcore:us-east-2:377311924364:runtime/faiston_schema_mapper-7fxI9bFHzd
      agent_session_id: 322cf6d0-6db3-47c4-a3ab-3abd1b179f96
    codebuild:
      project_name: null
      execution_role: null
      source_bucket: null
    memory:
      mode: STM_AND_LTM
      memory_id: faiston_schema_mapper_mem-JMkSnHFL67
      memory_arn: arn:aws:bedrock-agentcore:us-east-2:377311924364:memory/faiston_schema_mapper_mem-JMkSnHFL67
      memory_name: faiston_schema_mapper_mem
      event_expiry_days: 30
      first_invoke_memory_check_done: true
      was_created_by_toolkit: true
    identity:
      credential_providers: []
      workload: null
    aws_jwt:
      enabled: false
      audiences: []
      signing_algorithm: ES384
      issuer_url: null
      duration_seconds: 300
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
    api_key_env_var_name: null
    api_key_credential_provider_name: null
    is_generated_by_agentcore_create: false
  faiston_sga_debug:
    name: faiston_sga_debug
    entrypoint: agents/specialists/debug/main.py
    deployment_type: direct_code_deploy
    runtime_type: PYTHON_3_11
    platform: linux/arm64
    container_runtime: null
    source_path: .
    aws:
      execution_role: arn:aws:iam::377311924364:role/faiston-one-sga-agentcore-role
      execution_role_auto_create: false
      account: '377311924364'
      region: us-east-2
      ecr_repository: null
      ecr_auto_create: false
      s3_path: null
      s3_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: A2A
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: 300
        max_lifetime: 3600
    bedrock_agentcore:
      agent_id: faiston_sga_debug-W86Xdj8sAY
      agent_arn: arn:aws:bedrock-agentcore:us-east-2:377311924364:runtime/faiston_sga_debug-W86Xdj8sAY
      agent_session_id: null
    codebuild:
      project_name: null
      execution_role: null
      source_bucket: null
    memory:
      mode: STM_AND_LTM
      memory_id: faiston_sga_debug_memory-BZoY57FRmk
      memory_arn: null
      memory_name: faiston_sga_debug_memory
      event_expiry_days: 90
      first_invoke_memory_check_done: false
      was_created_by_toolkit: true
    identity:
      credential_providers: []
      workload: null
    aws_jwt:
      enabled: false
      audiences: []
      signing_algorithm: ES384
      issuer_url: null
      duration_seconds: 300
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
    api_key_env_var_name: null
    api_key_credential_provider_name: null
    is_generated_by_agentcore_create: false
